// <auto-generated />
namespace Lugares.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modelo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modelo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811140332368_Modelo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
